# Generated by Django 4.2 on 2025-10-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lasname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('level', models.CharField(max_length=70)),
            ],
        ),
    ]
