# Generated by Django 4.2 on 2025-10-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='lasname',
            new_name='lastname',
        ),
    ]
