# Generated by Django 4.2 on 2025-11-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_pokemon_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Electrico'), ('L', 'Lucha'), ('P', 'Planta'), ('F', 'Fuego'), ('A', 'Agua'), ('T', 'Tierra')], max_length=40),
        ),
    ]
