# Generated by Django 4.2 on 2025-11-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_pokemon_trainer_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Fuego', 'Fuego'), ('Lucha', 'Lucha'), ('Tierra', 'Tierra'), ('Electrico', 'Electrico'), ('Planta', 'Planta'), ('Agua', 'Agua')], max_length=40),
        ),
    ]
