# Generated by Django 4.2 on 2025-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_pokemon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_pictures/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Tierra', 'Tierra'), ('Planta', 'Planta'), ('Lucha', 'Lucha'), ('Electrico', 'Electrico'), ('Agua', 'Agua'), ('Fuego', 'Fuego')], max_length=40),
        ),
    ]
