# Generated by Django 4.2 on 2025-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_trainer_picture_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Electrico', 'Electrico'), ('Agua', 'Agua'), ('Fuego', 'Fuego'), ('Lucha', 'Lucha'), ('Tierra', 'Tierra'), ('Planta', 'Planta')], max_length=40),
        ),
    ]
