# Generated by Django 5.2.8 on 2025-12-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0009_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('Lucha', 'Lucha'), ('Electrico', 'Electrico'), ('Planta', 'Planta'), ('Agua', 'Agua'), ('Fuego', 'Fuego'), ('Tierra', 'Tierra')], max_length=40),
        ),
    ]
